---
- name: Update the cache
  become: true
  shell: yum -y update
  ignore_errors: true
  when: ansible_os_family == "RedHat"

- name: Add EPEL yum repository
  become: true
  yum_repository:
   name: epel
   description: EPEL YUM repo
   baseurl: https://download.fedoraproject.org/pub/epel/7/x86_64/
   gpgcheck: no

- name: Install required packages
  become: true
  package: name={{ item }} state=present
  with_items:
   - dnsmasq 
   - bridge-utils
   - genisoimage
   - expect
   - mlocate
   - zlib-devel
   - glib2-devel
   - ntfsprogs
   - ntfs-3g
   - nc
   - wget
   - git
   - gcc
   - qemu
   - python-pip
   - python-virtualenv

- pip:
   name: negotiator-host